In [2]:
import numpy as np

In [8]:
import numpy as np
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [7]:
ones_2d = np.ones((3,4))
print(ones_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
arr = np.linspace(0,1,11)
print(arr)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


PPT 넘파이 문제 1

In [12]:
A = np.array(
 [[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]]
 )

In [13]:
print(A.shape)

(5, 5)


In [14]:
print(A[3,3])

19


In [17]:
print(A[:2,:2])

[[1 2]
 [6 7]]


In [25]:
print(A[3:,3:])

[[19 20]
 [24 25]]


In [24]:
print(A[:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [27]:
print(A[:,-2:])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


PPT 넘파이 문제 2

In [30]:
B = np.array([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],

             [[13,14,15,16],
              [17,18,19,20],
              [21,22,23,24]],

             [[25,26,27,28],
              [29,30,31,32],
              [33,34,35,36]]])

In [37]:
b = np.arange(1,37)
B = b.reshape(3,3,4)
print(B)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [32]:
print(B.shape)
print(B.size)

(3, 3, 4)
36


In [34]:
print(B.reshape(3,4,3))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]


In [35]:
print(B.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
